[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

# CONFIGURAÇÃO DA PLACA EMISSORA
[env:ttgo_emissor]
upload_port = COM4
monitor_port = COM4
build_src_filter = +<*> -<receptor.cpp> -<main.cpp>
lib_deps =
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
    sandeepmistry/Lora

# CONFIGURAÇÃO DA PLACA RECEPTORA
[env:ttgo_receptor]
upload_port = COM3
monitor_port = COM3
build_src_filter = +<*> -<emissor.cpp> -<main.cpp>
lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git
    bblanchon/ArduinoJson
    sandeepmistry/Lora